<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/3/2
 * Time: 17:09
 */
namespace Register\Model;
use OCommon\Model\BaseModel;


/**
 * 注册Model
 */
class RegisterModel extends BaseModel {

    /**
     * 构造函数
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * 注册新增一个用户
     * @param $data
     * @return mixed
     */
    public function addData($data, $tableName = '')
    {
        return parent::addData($data, $tableName); // TODO: Change the autogenerated stub
    }


}